<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $registration->guest_number }} — {{ $event->name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f3f4f6; color: #111; }
        .container { max-width: 480px; margin: 0 auto; padding: 16px; }
        .card { background: #fff; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); overflow: hidden; }
        .header { background: {{ $category?->badge_color ?? '#2563EB' }}; color: #fff; padding: 20px; text-align: center; }
        .header h1 { font-size: 18px; font-weight: 600; }
        .header p { font-size: 13px; opacity: 0.9; margin-top: 4px; }
        .guest-number { font-size: 22px; font-weight: 700; letter-spacing: 1px; margin-top: 8px; font-family: monospace; }
        .body { padding: 20px; }
        .info-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6; font-size: 14px; }
        .info-row:last-child { border-bottom: none; }
        .info-label { color: #6b7280; }
        .info-value { font-weight: 500; text-align: right; }
        .qr-section { text-align: center; padding: 20px; background: #f9fafb; }
        .qr-section svg { width: 200px; height: 200px; }
        .status-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; padding: 16px 20px; }
        .status-box { text-align: center; padding: 10px; border-radius: 8px; font-size: 12px; font-weight: 600; }
        .status-done { background: #dcfce7; color: #166534; }
        .status-pending { background: #f3f4f6; color: #6b7280; }
        .category-badge { display: inline-block; background: {{ $category?->badge_color ?? '#6B7280' }}; color: #fff; padding: 3px 10px; border-radius: 4px; font-size: 12px; font-weight: 600; margin-top: 6px; }
        .footer { text-align: center; padding: 12px; font-size: 11px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="header">
                @if($event->logo_path)
                    <img src="{{ Storage::url($event->logo_path) }}" alt="{{ $event->name }}" style="max-height:40px;margin-bottom:8px;">
                @endif
                <h1>{{ $event->name }}</h1>
                <p>{{ $event->start_datetime?->format('M j, Y') }} &middot; {{ $event->venue }}</p>
                @if($category)
                    <span class="category-badge">{{ $category->name }}</span>
                @endif
                <div class="guest-number">{{ $registration->guest_number }}</div>
            </div>

            <div class="body">
                <div class="info-row">
                    <span class="info-label">Name</span>
                    <span class="info-value">{{ $registration->name }}</span>
                </div>
                @if($registration->designation)
                    <div class="info-row">
                        <span class="info-label">Designation</span>
                        <span class="info-value">{{ $registration->designation }}</span>
                    </div>
                @endif
                @if($registration->organization)
                    <div class="info-row">
                        <span class="info-label">Organization</span>
                        <span class="info-value">{{ $registration->organization }}</span>
                    </div>
                @endif
            </div>

            <div class="status-grid">
                <div class="status-box {{ $registration->hasEntered() ? 'status-done' : 'status-pending' }}">
                    {{ $registration->hasEntered() ? 'Checked In' : 'Not Checked In' }}
                </div>
                <div class="status-box {{ $registration->hasUsedMeal('lunch') ? 'status-done' : 'status-pending' }}">
                    {{ $registration->hasUsedMeal('lunch') ? 'Lunch Taken' : 'Lunch Pending' }}
                </div>
                <div class="status-box {{ $registration->hasUsedMeal('dinner') ? 'status-done' : 'status-pending' }}">
                    {{ $registration->hasUsedMeal('dinner') ? 'Dinner Taken' : 'Dinner Pending' }}
                </div>
            </div>

            <div class="qr-section">
                {!! $qrSvg !!}
            </div>
        </div>

        <div class="footer">
            Generated by {{ config('app.name') }} &middot; {{ now()->format('Y-m-d H:i') }}
        </div>
    </div>
</body>
</html>
